config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to @flat, notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to @flat, notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy
    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <div class="form">
    <h1>Edit <%= @flat.name %></h1>
    <%= render 'shared/form', flat: @flat %>
  </div>
  <%= link_to @flat, class: "btn btn-outline-secondary" do %>
    <p class="m-0"><i class="fas fa-angle-left"></i> Back</p>
  <% end %>
  <%= link_to flats_path, class: "btn btn-outline-secondary" do %>
    <p class="m-0"><i class="fas fa-home"></i> Home</p>
  <% end %>
</div>

app/views/flats/index.html.erb
<%= render 'shared/banner', img_path: "https://images.pexels.com/photos/279719/pexels-photo-279719.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940", flat: "Flats" %>
<div class="container">
  <div class="card-result mt-5">
    <% if @query %>
      <p>You searched <strong><%= @query %></strong>. <%= @flats.count %> out of <%= Flat.count %> flats are found.</p>
    <% else %>
      <p>All <%= Flat.count %> Flats</p>
    <% end %>
  </div>
  <div class="cards m-5">
    <% @flats.each do |flat| %>
      <div class="card-body" data-id="<%= flat.id %>">
        <p class="card-title m-0"><%= flat.name %></p>
        <p class="m-0"><i class="fas fa-map-marker-alt"></i> <%= flat.address %></p>
        <p class="m-0"><i class="fas fa-yen-sign"></i> <%= flat.price_per_night %> per night</p>
        <p class="m-0"><i class="fas fa-users"></i> <%= flat.number_of_guests %></p>
        <div class="d-flex justify-content-between mt-2">
          <%= link_to flat_path(flat) do %>
            <p id="more-info" class="mb-0"><i class="fas fa-info-circle"></i> More Info</p> 
          <% end %>
          <%= link_to edit_flat_path(flat) do %>
            <p id="edit" class="mb-0"><i class="fas fa-edit"></i> Edit</p>
          <% end %>
          <%= link_to flats_path, data: { confirm: "Are you sure?"} do %>
            <p id="delete" class="mb-0"><i class="fas fa-trash-alt"></i> Delete</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="form">
  <h1>Add a Flat</h1>
  <%= render 'shared/form', flat: @flat %>
</div>
<%= link_to flats_path, class: "btn btn-outline-secondary" do %>
  <p class="m-0"><i class="fas fa-angle-left"></i> Back</p>
<% end %>

app/views/flats/show.html.erb
<%= render 'shared/banner', img_path: "https://source.unsplash.com/1600x900/?bedroom", flat: @flat.name %>
<div class="container my-5">
  <div class="card-info">
    <p class="m-0"><i class="fas fa-map-marker-alt"></i> <%= @flat.address %></p>
    <p class="m-0"><i class="fas fa-info-circle"></i> <%= @flat.description %></p>
    <p class="m-0"><i class="fas fa-yen-sign"></i> <%= @flat.price_per_night %> per night</p>
    <p class="m-0"><i class="fas fa-users"></i> <%= @flat.number_of_guests %></p>
  </div>
  <%= link_to flats_path, class: "btn btn-outline-secondary mt-4" do %>
    <p class="m-0"><i class="fas fa-angle-left"></i> Back</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(255,255,255,0.4),rgba(255,255,255,0.4)), url(<%= img_path %>)">
  <div class="container p-0">
    <h1><%= flat %></h1>
  </div>
</div>

app/views/shared/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.input :name, placeholder: "Kenny Smith" %>
  <%= f.input :address, placeholder: "1-2-3 Marunouchi, Chiyoda-ku" %>
  <%= f.input :description, placeholder: "Huge yard in front of the house, one master bedroom with king-sized bed..." %>
  <%= f.input :price_per_night, placeholder: "1000" %>
  <%= f.input :number_of_guests, prompt: "Please select", collection: 1..20 %>
  <% if @flat.id %>
    <%= f.submit "Update", class:"btn btn-outline-success mt-4" %>
  <% else %>
    <%= f.submit "Add a Flat", class:"btn btn-outline-primary mt-4" %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark bg-gradient">
  <div class="container-fluid">
      <img src="https://image.flaticon.com/icons/png/128/609/609803.png" alt="logo" width="30" height="24" class="d-inline-block align-text-top">
      <%= link_to "Flat Finder", :root, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <div class="ml-2 d-flex">
        <form class="form-inline d-flex my-2 my-lg-0">
          <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search" value="<%= params[:query] %>">
          <button class="btn btn-outline-info" type="submit">Search</button>
        </form>
        <%= link_to "Add a Flat", new_flat_path, class: "btn btn-outline-primary ml-2" %>
     </div>
    </div>
  </div>
</nav>